### ISSUE TITLE
NuGet references are not resolved

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#14]
I have a T4 file which imports an assembly reference from NuGet (the project depends on this assembly). This works in VS, but an "unresolved assembly" error is shown in Rider 2019.3 EAP 6:

![image](https://user-images.githubusercontent.com/7913492/69532712-b70f1d00-0f76-11ea-86c2-ced03e80b048.png)

Also, the T4 file doesn't execute automatically, and I don't see any error message (there's nothing in the event log anyway).

Here's the T4 file:
https://github.com/ltrzesniewski/InlineIL.Fody/blob/d928226008705a0adf5a38650e674c062af59adc/src/InlineIL/IL.Emit.tt

**Comment by ltrzesniewski** [comment]
Oh, I just noticed the "execute template" action, if I run it I get the following error:

![image](https://user-images.githubusercontent.com/7913492/69533461-276a6e00-0f78-11ea-827e-30914b9d589b.png)

**Comment by kirillgla** [comment]
Thank you for the report! I'll work on that

**Comment by kirillgla** [comment]
@ltrzesniewski, could you explain how exactly this should work, please? According to [StackOverflow](https://stackoverflow.com/questions/3434713/cant-reference-an-assembly-in-a-t4-template), it is not possible to reference a NuGet package from T4 template like that

**Comment by kirillgla** [comment]
I tried doing the same trick with another NuGet package (`JavaScriptEngineSwitcher.Core`). I referenced it in a project that contains the template, but Visual Studio 2019 still refuses to compile a template references that package. Is there anything I'm missing?

**Comment by kirillgla** [comment]
By the way, a workaround suggested my many resources is to use VS macros like that:
```
<#@ assembly name="$(SolutionDir)packages\...<path to the NuGet you want>" #>
```

**Comment by ltrzesniewski** [comment]
Well, I didn't do anything in particular, it usually just worked in VS for me.

I just tried the following: I made a fresh clone of [InlineIL.Fody](https://github.com/ltrzesniewski/InlineIL.Fody) on my work computer and edited the IL.Emit.tt template. I got the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Mono.Cecil'.
File name: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Mono.Cecil'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.<>c.<.ctor>b__15_0(String x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilation()
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable`1 references, Boolean debug, SupportedLanguage language, String compilerOptions)	InlineIL.Fody		1	
```

I then reverted the IL.Emit.cs file and compiled the project then tried to generate the template again. It still failed.

Quite honestly I'm very surprised, I suppose I must have some version of Moco.Cecil in the GAC on my home PC where this thing works fine. I guess I'll need to use a workaround similar to what you suggested.

Thanks for looking into this, and sorry for the trouble.
