### ISSUE TITLE
Debugging with ForTea 2021.1.0 throws FileLoadException: Microsoft.VisualStudio.Validation 16.8.0.0

### ISSUE THREAD

**Issue by axunonb** [JetBrains/ForTea#45]
**ForTea 2021.1.0 running on ReSharper 2021.1.1**

* The T4 succeeds to execute with expected result,
* but throws "Template runtime error" source "TemporaryT4Assembly" when trying to debug

FileLoadException: Die Datei oder Assembly "Microsoft.VisualStudio.Validation, Version=16.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
   at Microsoft.VisualStudio.TextTemplatingD2F944D76AED1C6ACD22519EC6CD3F1A231C9AC42E8CA9640D4E5FECE9AA8882BCDC4C658C005F80F21B20F613021080E0C630AB8D0F4755C5058E01356159F8.GeneratedTextTransformation.TransformText() in xyz.tt:line 84
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()

**Comment by ichalyshev** [comment]
This helped me

How to Fix the T4 Debugger in Visual Studio 16.9.X

https://improveandrepeat.com/2021/05/how-to-fix-the-t4-debugger-in-visual-studio-16-9-x/

**Comment by axunonb** [comment]
Wonderful, works perfectly. Thanks a lot, you saved my day.

**Comment by ichalyshev** [comment]
Always welcome axunonb! You are doing the great job, ForTea is absolutely excellent plugin! Thank you!
